export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const HRM_SAU_REQUEST = 'HRM_SAU_REQUEST'
export const HRM_SAU_SUCCESS = 'HRM_SAU_SUCCESS'
export const HRM_SAU_FAILURE = 'HRM_SAU_FAILURE'

export const PROCESS_DEFINITION_REQUEST = 'PROCESS_DEFINITION_REQUEST'
export const PROCESS_DEFINITION_SUCCESS = 'PROCESS_DEFINITION_SUCCESS'
export const PROCESS_DEFINITION_FAILURE = 'PROCESS_DEFINITION_FAILURE'

export const PROCESS_DEFINITION_XML_REQUEST = 'PROCESS_DEFINITION_XML_REQUEST'
export const PROCESS_DEFINITION_XML_SUCCESS = 'PROCESS_DEFINITION_XML_SUCCESS'
export const PROCESS_DEFINITION_XML_FAILURE = 'PROCESS_DEFINITION_XML_FAILURE'

export const GET_PERSONAL_REQUEST = 'GET_PERSONAL_REQUEST'
export const GET_PERSONAL_SUCCESS = 'GET_PERSONAL_SUCCESS'
export const GET_PERSONAL_FAILURE = 'GET_PERSONAL_FAILURE'

export const UPDATE_PERSONAL_REQUEST = 'UPDATE_PERSONAL_REQUEST'
export const UPDATE_PERSONAL_SUCCESS = 'UPDATE_PERSONAL_SUCCESS'
export const UPDATE_PERSONAL_FAILURE = 'UPDATE_PERSONAL_FAILURE'

export const NEW_PROCESS_INSTANCE_REQUEST = 'NEW_PROCESS_INSTANCE_REQUEST'
export const NEW_PROCESS_INSTANCE_SUCCESS = 'NEW_PROCESS_INSTANCE_SUCCESS'
export const NEW_PROCESS_INSTANCE_FAILURE = 'NEW_PROCESS_INSTANCE_FAILURE'

export const NEW_PROCESS_INSTANCE_VARIABLES_REQUEST = 'NEW_PROCESS_INSTANCE_VARIABLES_REQUEST'
export const NEW_PROCESS_INSTANCE_VARIABLES_SUCCESS = 'NEW_PROCESS_INSTANCE_VARIABLES_SUCCESS'
export const NEW_PROCESS_INSTANCE_VARIABLES_FAILURE = 'NEW_PROCESS_INSTANCE_VARIABLES_FAILURE'

export const FORM_KEY_REQUEST = 'FORM_KEY_REQUEST'
export const FORM_KEY_SUCCESS = 'FORM_KEY_SUCCESS'
export const FORM_KEY_FAILURE = 'FORM_KEY_FAILURE'

export const TASKS_REQUEST = 'TASKS_REQUEST'
export const TASKS_SUCCESS = 'TASKS_SUCCESS'
export const TASKS_FAILURE = 'TASKS_FAILURE'

export const TASK_FORM_KEY_REQUEST = 'TASK_FORM_KEY_REQUEST'
export const TASK_FORM_KEY_SUCCESS = 'TASK_FORM_KEY_SUCCESS'
export const TASK_FORM_KEY_FAILURE = 'TASK_FORM_KEY_FAILURE'

export const TASK_SUBMITTED_REQUEST = 'TASK_SUBMITTED_REQUEST'
export const TASK_SUBMITTED_SUCCESS = 'TASK_SUBMITTED_SUCCESS'
export const TASK_SUBMITTED_FAILURE = 'TASK_SUBMITTED_FAILURE'

export const TASK_VARIABLES_REQUEST = 'TASK_VARIABLES_REQUEST'
export const TASK_VARIABLES_SUCCESS = 'TASK_VARIABLES_SUCCESS'
export const TASK_VARIABLES_FAILURE = 'TASK_VARIABLES_FAILURE'

export const PROCESS_DEPLOYMENT_REQUEST = 'PROCESS_DEPLOYMENT_REQUEST'
export const PROCESS_DEPLOYMENT_SUCCESS = 'PROCESS_DEPLOYMENT_SUCCESS'
export const PROCESS_DEPLOYMENT_FAILURE = 'PROCESS_DEPLOYMENT_FAILURE'
//              BACKEND API'S
export const INITIATE_GET_DATA_REQUEST = 'INITIATE_GET_DATA_REQUEST';
export const INITIATE_GET_DATA_SUCCESS = 'INITIATE_GET_DATA_SUCCESS';
export const INITIATE_GET_DATA_FAILURE = 'INITIATE_GET_DATA_FAILURE';

export const GET_DEPT_REQUEST = 'GET_DEPT_REQUEST';
export const GET_DEPT_SUCCESS = 'GET_DEPT_SUCCESS';
export const GET_DEPT_FAILURE = 'GET_DEPT_FAILURE';

export const INITIATE_FORM_CREATE_REQUEST = 'INITIATE_FORM_CREATE_REQUEST';
export const INITIATE_FORM_CREATE_SUCCESS = 'INITIATE_FORM_CREATE_SUCCESS';
export const INITIATE_FORM_CREATE_FAILURE = 'INITIATE_FORM_CREATE_FAILURE';

export const CLASSIFICATION_REQUEST = 'CLASSIFICATION_REQUEST'
export const CLASSIFICATION_SUCCESS = 'CLASSIFICATION_SUCCESS'
export const CLASSIFICATION_FAILURE = 'CLASSIFICATION_FAILURE'

export const PA_DASHBOARD_REQUEST = 'PA_DASHBOARD_REQUEST'
export const PA_DASHBOARD_SUCCESS = 'PA_DASHBOARD_SUCCESS'
export const PA_DASHBOARD_FAILURE = 'PA_DASHBOARD_FAILURE'

export const TYPE_REQUEST = 'TYPE_REQUEST'
export const TYPE_SUCCESS = 'TYPE_SUCCESS'
export const TYPE_FAILURE = 'TYPE_FAILURE'

export const ROLES_REQUEST = 'ROLES_REQUEST'
export const ROLES_SUCCESS = 'ROLES_SUCCESS'
export const ROLES_FAILURE = 'ROLES_FAILURE'

export const GROUPS_REQUEST = 'GROUPS_REQUEST'
export const GROUPS_SUCCESS = 'GROUPS_SUCCESS'
export const GROUPS_FAILURE = 'GROUPS_FAILURE'

export const DRAFT_DATA_REQUEST = 'DRAFT_DATA_REQUEST'
export const DRAFT_DATA_SUCCESS = 'DRAFT_DATA_SUCCESS'
export const DRAFT_DATA_FAILURE = 'DRAFT_DATA_FAILURE'

export const OUTBOX_DATA_REQUEST = 'OUTBOX_DATA_REQUEST'
export const OUTBOX_DATA_SUCCESS = 'OUTBOX_DATA_SUCCESS'
export const OUTBOX_DATA_FAILURE = 'OUTBOX_DATA_FAILURE'

export const OUTBOX_DATA_EXPORT_REQUEST = 'OUTBOX_DATA_EXPORT_REQUEST'
export const OUTBOX_DATA_EXPORT_SUCCESS = 'OUTBOX_DATA_EXPORT_SUCCESS'
export const OUTBOX_DATA_EXPORT_FAILURE = 'OUTBOX_DATA_EXPORT_FAILURE'

export const OUTBOX_ROW_REQUEST = 'OUTBOX_ROW_REQUEST'
export const OUTBOX_ROW_SUCCESS = 'OUTBOX_ROW_SUCCESS'
export const OUTBOX_ROW_FAILURE = 'OUTBOX_ROW_FAILURE'

export const INBOX_DATA_REQUEST = 'INBOX_DATA_REQUEST'
export const INBOX_DATA_SUCCESS = 'INBOX_DATA_SUCCESS'
export const INBOX_DATA_FAILURE = 'INBOX_DATA_FAILURE'

export const ENCLOSURE_DATA_REQUEST = 'ENCLOSURE_DATA_REQUEST'
export const ENCLOSURE_DATA_SUCCESS = 'ENCLOSURE_DATA_SUCCESS'
export const ENCLOSURE_DATA_FAILURE = 'ENCLOSURE_DATA_FAILURE'

export const NOTING_DATA_REQUEST = 'NOTING_DATA_REQUEST'
export const NOTING_DATA_SUCCESS = 'NOTING_DATA_SUCCESS'
export const NOTING_DATA_FAILURE = 'NOTING_DATA_FAILURE'

export const NOTING_FILE_REQUEST = 'NOTING_FILE_REQUEST'
export const NOTING_FILE_SUCCESS = 'NOTING_FILE_SUCCESS'
export const NOTING_FILE_FAILURE = 'NOTING_FILE_FAILURE'

export const ENCLOSURE_FILE_REQUEST = 'ENCLOSURE_FILE_REQUEST'
export const ENCLOSURE_FILE_SUCCESS = 'ENCLOSURE_FILE_SUCCESS'
export const ENCLOSURE_FILE_FAILURE = 'ENCLOSURE_FILE_FAILURE'

export const SEND_FILE_REQUEST = 'SEND_FILE_REQUEST'
export const SEND_FILE_SUCCESS = 'SEND_FILE_SUCCESS'
export const SEND_FILE_FAILURE = 'SEND_FILE_FAILURE'

export const FILE_REQUEST = 'FILE_REQUEST'
export const FILE_SUCCESS = 'FILE_SUCCESS'
export const FILE_FAILURE = 'FILE_FAILURE'

export const SFDT_REQUEST = 'SFDT_REQUEST'
export const SFDT_SUCCESS = 'SFDT_SUCCESS'
export const SFDT_FAILURE = 'SFDT_FAILURE'

export const TEST_URL_REQUEST = 'TEST_URL_REQUEST'
export const TEST_URL_SUCCESS = 'TEST_URL_SUCCESS'
export const TEST_URL_FAILURE = 'TEST_URL_FAILURE'

export const CREATE_PF_REQUEST = 'CREATE_PF_REQUEST'
export const CREATE_PF_SUCCESS = 'CREATE_PF_SUCCESS'
export const CREATE_PF_FAILURE = 'CREATE_PF_FAILURE'

export const PA_REQUEST = 'PA_REQUEST'
export const PA_SUCCESS = 'PA_SUCCESS'
export const PA_FAILURE = 'PA_FAILURE'

export const UPDATE_SUBJECT_DRAFT_REQUEST = "UPDATE_SUBJECT_DRAFT_REQUEST"
export const UPDATE_SUBJECT_DRAFT_SUCCESS = "UPDATE_SUBJECT_DRAFT_SUCCESS"
export const UPDATE_SUBJECT_DRAFT_FAILURE = "UPDATE_SUBJECT_DRAFT_FAILURE"

export const PATYPE_REQUEST = 'PATYPE_REQUEST'
export const PATYPE_SUCCESS = 'PATYPE_SUCCESS'
export const PATYPE_FAILURE = 'PATYPE_FAILURE'

export const PF_REQUEST = 'PF_REQUEST'
export const PF_SUCCESS = 'PF_SUCCESS'
export const PF_FAILURE = 'PF_FAILURE'

export const PFILE_REQUEST = 'PFILE_REQUEST'
export const PFILE_SUCCESS = 'PFILE_SUCCESS'
export const PFILE_FAILURE = 'PFILE_FAILURE'

export const PA_TABLE_REQUEST = 'PA_TABLE_REQUEST'
export const PA_TABLE_SUCCESS = 'PA_TABLE_SUCCESS'
export const PA_TABLE_FAILURE = 'PA_TABLE_FAILURE'

export const ANNOT_REQUEST = 'ANNOT_REQUEST'
export const ANNOT_SUCCESS = 'ANNOT_SUCCESS'
export const ANNOT_FAILURE = 'ANNOT_FAILURE'

export const GET_ANNOT_REQUEST = 'GET_ANNOT_REQUEST'
export const GET_ANNOT_SUCCESS = 'GET_ANNOT_SUCCESS'
export const GET_ANNOT_FAILURE = 'GET_ANNOT_FAILURE'

export const SEND_FILES_REQUEST = 'SEND_FILES_REQUEST'
export const SEND_FILES_SUCCESS = 'SEND_FILES_SUCCESS'
export const SEND_FILES_FAILURE = 'SEND_FILES_FAILURE'

export const QICK_SIGN_REQUEST = 'QICK_SIGN_REQUEST'
export const QICK_SIGN_SUCCESS = 'QICK_SIGN_SUCCESS'
export const QICK_SIGN_FAILURE = 'QICK_SIGN_FAILURE'

export const SAVE_FILES_REQUEST = 'SAVE_FILES_REQUEST'
export const SAVE_FILES_SUCCESS = 'SAVE_FILES_SUCCESS'
export const SAVE_FILES_FAILURE = 'SAVE_FILES_FAILURE'

export const ANNEXURE_FILE_REQUEST = 'ANNEXURE_FILE_REQUEST'
export const ANNEXURE_FILE_SUCCESS = 'ANNEXURE_FILE_SUCCESS'
export const ANNEXURE_FILE_FAILURE = 'ANNEXURE_FILE_FAILURE'

export const ANNEXURE_LIST_REQUEST = 'ANNEXURE_LIST_REQUEST'
export const ANNEXURE_LIST_SUCCESS = 'ANNEXURE_LIST_SUCCESS'
export const ANNEXURE_LIST_FAILURE = 'ANNEXURE_LIST_FAILURE'

export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST'
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS'
export const GROUP_LIST_FAILURE = 'GROUP_LIST_FAILURE'

export const HRM_LIST_REQUEST = 'HRM_LIST_REQUEST'
export const HRM_LIST_SUCCESS = 'HRM_LIST_SUCCESS'
export const HRM_LIST_FAILURE = 'HRM_LIST_FAILURE'

export const USER_ROLES_REQUEST = 'USER_ROLES_REQUEST'
export const USER_ROLES_SUCCESS = 'USER_ROLES_SUCCESS'
export const USER_ROLES_FAILURE = 'USER_ROLES_FAILURE'

export const MIS_LIST_REQUEST = 'MIS_LIST_REQUEST'
export const MIS_LIST_SUCCESS = 'MIS_LIST_SUCCESS'
export const MIS_LIST_FAILURE = 'MIS_LIST_FAILURE'

export const MIS_DETAIL_LIST_REQUEST = 'MIS_DETAIL_LIST_REQUEST'
export const MIS_DETAIL_LIST_SUCCESS = 'MIS_DETAIL_LIST_SUCCESS'
export const MIS_DETAIL_LIST_FAILURE = 'MIS_DETAIL_LIST_FAILURE'

export const DELETE_ANNEXURE_REQUEST = 'DELETE_ANNEXURE_REQUEST'
export const DELETE_ANNEXURE_SUCCESS = 'DELETE_ANNEXURE_SUCCESS'
export const DELETE_ANNEXURE_FAILURE = 'DELETE_ANNEXURE_FAILURE'

export const CREATE_PANOTING_REQUEST = 'CREATE_PANOTING_REQUEST'
export const CREATE_PANOTING_SUCCESS = 'CREATE_PANOTING_SUCCESS'
export const CREATE_PANOTING_FAILURE = 'CREATE_PANOTING_FAILURE'

export const FETCH_PANOTING_REQUEST = 'FETCH_PANOTING_REQUEST'
export const FETCH_PANOTING_SUCCESS = 'FETCH_PANOTING_SUCCESS'
export const FETCH_PANOTING_FAILURE = 'FETCH_PANOTING_FAILURE'

export const FETCH_PAENCLOSURE_REQUEST = 'FETCH_PAENCLOSURE_REQUEST'
export const FETCH_PAENCLOSURE_SUCCESS = 'FETCH_PAENCLOSURE_SUCCESS'
export const FETCH_PAENCLOSURE_FAILURE = 'FETCH_PAENCLOSURE_FAILURE'

export const FETCH_SECTION_REQUEST = 'FETCH_SECTION_REQUEST'
export const FETCH_SECTION_SUCCESS = 'FETCH_SECTION_SUCCESS'
export const FETCH_SECTION_FAILURE = 'FETCH_SECTION_FAILURE'

export const FETCH_SERVICENUMBER_REQUEST = 'FETCH_SERVICENUMBER_REQUEST'
export const FETCH_SERVICENUMBER_SUCCESS = 'FETCH_SERVICENUMBER_SUCCESS'
export const FETCH_SERVICENUMBER_FAILURE = 'FETCH_SERVICENUMBER_FAILURE'

export const SENDFILESECTION_REQUEST = 'SENDFILESECTION_REQUEST'
export const SENDFILESECTION_SUCCESS = 'SENDFILESECTION_SUCCESS'
export const SENDFILESECTION_FAILURE = 'SENDFILESECTION_FAILURE'

export const SENDFILESERVICENUMBER_REQUEST = 'SENDFILESERVICENUMBER_REQUEST'
export const SENDFILESERVICENUMBER_SUCCESS = 'SENDFILESERVICENUMBER_SUCCESS'
export const SENDFILESERVICENUMBER_FAILURE = 'SENDFILESERVICENUMBER_FAILURE'

export const PADRAFT_REQUEST = 'PADRAFT_REQUEST'
export const PADRAFT_SUCCESS = 'PADRAFT_SUCCESS'
export const PADRAFT_FAILURE = 'PADRAFT_FAILURE'

export const PART_CASE_DATA_REQUEST = 'PART_CASE_DATA_REQUEST'
export const PART_CASE_DATA_SUCCESS = 'PART_CASE_DATA_SUCCESS'
export const PART_CASE_DATA_FAILURE = 'PART_CASE_DATA_FAILURE'

export const SPLITVIEW_INBOXDATA_REQUEST = 'SPLITVIEW_INBOXDATA_REQUEST'
export const SPLITVIEW_INBOXDATA_SUCCESS = 'SPLITVIEW_INBOXDATA_SUCCESS'
export const SPLITVIEW_INBOXDATA_FAILURE = 'SPLITVIEW_INBOXDATA_FAILURE'

export const PA_FILE_DATA_REQUEST = 'PA_FILE_DATA_REQUEST'
export const PA_FILE_DATA_SUCCESS = 'PA_FILE_DATA_SUCCESS'
export const PA_FILE_DATA_FAILURE = 'PA_FILE_DATA_FAILURE'

export const PARTCASE_TAG_REQUEST = 'PARTCASE_TAG_REQUEST'
export const PARTCASE_TAG_SUCCESS = 'PARTCASE_TAG_SUCCESS'
export const PARTCASE_TAG_FAILURE = 'PARTCASE_TAG_FAILURE'

export const FETCH_PARTCASE_TAG_REQUEST = 'FETCH_PARTCASE_TAG_REQUEST'
export const FETCH_PARTCASE_TAG_SUCCESS = 'FETCH_PARTCASE_TAG_SUCCESS'
export const FETCH_PARTCASE_TAG_FAILURE = 'FETCH_PARTCASE_TAG_FAILURE'

export const CREATE_PARTCASE_NOTING_REQUEST = 'CREATE_PARTCASE_NOTING_REQUEST'
export const CREATE_PARTCASE_NOTING_SUCCESS = 'CREATE_PARTCASE_NOTING_SUCCESS'
export const CREATE_PARTCASE_NOTING_FAILURE = 'CREATE_PARTCASE_NOTING_FAILURE'

export const CREATE_COVER_LETTER_REQUEST = 'CREATE_COVER_LETTER_REQUEST'
export const CREATE_COVER_LETTER_SUCCESS = 'CREATE_COVER_LETTER_SUCCESS'
export const CREATE_COVER_LETTER_FAILURE = 'CREATE_COVER_LETTER_FAILURE'

export const UPDATE_PARTCASE_STATUS_REQUEST = 'UPDATE_PARTCASE_STATUS_REQUEST'
export const UPDATE_PARTCASE_STATUS_SUCCESS = 'UPDATE_PARTCASE_STATUS_SUCCESS'
export const UPDATE_PARTCASE_STATUS_FAILURE = 'UPDATE_PARTCASE_STATUS_FAILURE'

export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE'

export const SENDFILEINTERNALSERVICENUMBER_REQUEST = 'SENDFILEINTERNALSERVICENUMBER_REQUEST'
export const SENDFILEINTERNALSERVICENUMBER_SUCCESS = 'SENDFILEINTERNALSERVICENUMBER_SUCCESS'
export const SENDFILEINTERNALSERVICENUMBER_FAILURE = 'SENDFILEINTERNALSERVICENUMBER_FAILURE'

export const FETCH_INTERNALSERVICENUMBER_REQUEST = 'FETCH_INTERNALSERVICENUMBER_REQUEST'
export const FETCH_INTERNALSERVICENUMBER_SUCCESS = 'FETCH_INTERNALSERVICENUMBER_SUCCESS'
export const FETCH_INTERNALSERVICENUMBER_FAILURE = 'FETCH_INTERNALSERVICENUMBER_FAILURE'

export const THEME_CHANGE = 'THEME_CHANGE'
export const OPEN_PA_DRAFT = 'OPEN_PA_DRAFT'
export const CHANGE_PA_FILE = 'CHANGE_PA_FILE'
export const MYINFO_CHANGE = 'MYINFO_CHANGE'

export const FETCH_PAWITHANNEXURE_REQUEST = 'FETCH_PAWITHANNEXURE_REQUEST'
export const FETCH_PAWITHANNEXURE_SUCCESS = 'FETCH_PAWITHANNEXURE_SUCCESS'
export const FETCH_PAWITHANNEXURE_FAILURE = 'FETCH_PAWITHANNEXURE_FAILURE'

export const ROLLBACK_PA_REQUEST = 'ROLLBACK_PA_REQUEST'
export const ROLLBACK_PA_SUCCESS = 'ROLLBACK_PA_SUCCESS'
export const ROLLBACK_PA_FAILURE = 'ROLLBACK_PA_FAILURE'

export const ADD_TO_FAVOURITE_REQUEST = 'ADD_TO_FAVOURITE_REQUEST'
export const ADD_TO_FAVOURITE_SUCCESS = 'ADD_TO_FAVOURITE_SUCCESS'
export const ADD_TO_FAVOURITE_FAILURE = 'ADD_TO_FAVOURITE_FAILURE'

export const FETCH_FAVOURITE_LIST_REQUEST = 'FETCH_FAVOURITE_LIST_REQUEST'
export const FETCH_FAVOURITE_LIST_SUCCESS = 'FETCH_FAVOURITE_LIST_SUCCESS'
export const FETCH_FAVOURITE_LIST_FAILURE = 'FETCH_FAVOURITE_LIST_FAILURE'

export const DELETE_FAVOURITE_REQUEST = 'DELETE_FAVOURITE_REQUEST'
export const DELETE_FAVOURITE_SUCCESS = 'DELETE_FAVOURITE_SUCCESS'
export const DELETE_FAVOURITE_FAILURE = 'DELETE_FAVOURITE_FAILURE'


export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST'
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS'
export const GET_NOTIFICATION_FAILURE = 'GET_NOTIFICATION_FAILURE'

export const STATUS_NOTIFICATION_REQUEST = 'STATUS_NOTIFICATION_REQUEST'
export const STATUS_NOTIFICATION_SUCCESS = 'STATUS_NOTIFICATION_SUCCESS'
export const STATUS_NOTIFICATION_FAILURE = 'STATUS_NOTIFICATION_FAILURE'

export const DELETE_NOTIFICATION_REQUEST = 'DELETE_NOTIFICATION_REQUEST'
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS'
export const DELETE_NOTIFICATION_FAILURE = 'DELETE_NOTIFICATION_FAILURE'

export const DELETE_ALL_NOTIFICATION_REQUEST = 'DELETE_ALL_NOTIFICATION_REQUEST'
export const DELETE_ALL_NOTIFICATION_SUCCESS = 'DELETE_ALL_NOTIFICATION_SUCCESS'
export const DELETE_ALL_NOTIFICATION_FAILURE = 'DELETE_ALL_NOTIFICATION_FAILURE'

export const RETURN_PA_REQUEST = 'RETURN_PA_REQUEST'
export const RETURN_PA_SUCCESS = 'RETURN_PA_SUCCESS'
export const RETURN_PA_FAILURE = 'RETURN_PA_FAILURE'